# NumPy Basics for Quantum Computing

This notebook is designed for a frontend developer refreshing Python and learning NumPy for quantum software development.

## Goal

Learn NumPy basics because quantum states, gates, and measurement results are easier to work with using arrays.

You will practice:

- `np.array()`
- 1D arrays
- 2D arrays
- array shape
- indexing
- slicing
- `np.zeros()`
- `np.ones()`
- `np.eye()`
- `np.sqrt()`
- Python lists vs NumPy arrays
- quantum states as vectors
- quantum gates as matrices
- probabilities from amplitudes
- basic gate application
- tensor product using `np.kron()`

## Setup

Run this first.

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 1. `np.array()`


`np.array()` creates a NumPy array from Python data like lists.

In quantum computing, we use arrays to represent state vectors and matrices.

### Example

In [3]:
import numpy as np

state = np.array([1, 0])
print(state)
print(type(state))

[1 0]
<class 'numpy.ndarray'>


### Practice Questions

1. Create a NumPy array from `[1, 0]`.
2. Create a NumPy array from `[0, 1]`.
3. Create a NumPy array from `[1, 2, 3, 4]`.
4. Print the type of a NumPy array.
5. Create an array of floating-point values `[0.5, 0.25, 0.25]`.
6. Create an array from a nested list `[[1, 0], [0, 1]]`.
7. Create an array representing the quantum state `|0⟩`.
8. Create an array representing the quantum state `|1⟩`.
9. Create an array representing probabilities `[0.5, 0.5]`.
10. Create an array representing measurement counts `[45, 55]`.
11. Convert the Python list `[10, 20, 30]` into a NumPy array.
12. Create an array with negative values `[1, -1]`.
13. Create an array with decimal amplitudes `[0.707, 0.707]`.
14. Print your array values using `print()`.
15. Create any custom array and explain what each value could represent in quantum computing.

In [4]:
# Practice workspace
import numpy as np
# Write your answers here

# 1.  Create a NumPy array from `[1, 0]`.
zero_state = np.array([1,0])
print("Answer1: ", zero_state)
# 2. Create a NumPy array from `[0, 1]`.
one_state = np.array([0,1])
print("Answer2: ", one_state)
# 3. Create a NumPy array from `[1, 2, 3, 4]`.
arr3 = np.array([1,2,3,4])
print("Answer3: ", arr3)
# 4. Print the type of a NumPy array.
print("Answer4: ",type(arr3))
# 5. Create an array of floating-point values `[0.5, 0.25, 0.25]`.
arr5 = np.array([0.5,0.25,0.25])
print("Answer5: ", arr5)
# 6. Create an array from a nested list `[[1, 0], [0, 1]]`.
I = np.array([
    [1,0],
    [0,1]
])
# I = np.eye(2)
print(I, ": Answer6")
# 7. Create an array representing the quantum state `|0⟩`.
v_zero = np.array([1,0])
print("Answer7: ", v_zero)
# 8. Create an array representing the quantum state `|1⟩`.
v_one = np.array([0,1])
print("Answer8: ", v_one)
# 9. Create an array representing probabilities `[0.5, 0.5]`.
arr9 = np.array([0.5,0.5])
print("Answer9: ",arr9)
# 10. Create an array representing measurement counts `[45, 55]`.
arr10 = np.array([45,55])
print("Answer10: ",arr10)
# 11. Convert the Python list `[10, 20, 30]` into a NumPy array.
my_list = [10,20,30]
arr11 = np.array(my_list)
print("Answer11: ",arr11)
# 12. Create an array with negative values `[1, -1]`.
arr12 = np.array([1,-1])
print("Answer12: ",arr12)
# 13. Create an array with decimal amplitudes `[0.707, 0.707]`.
amplitudes = [0.707,0.707]
arr13 = np.array(amplitudes)
print("Answer13: ",arr13)
# 14. Print your array values using `print()`.
# 15. Create any custom array and explain what each value could represent in quantum computing.
custom_state = np.array([0.6, 0.8])
print("Answer15:", custom_state)

print("0.6 is amplitude of |0⟩")
print("0.8 is amplitude of |1⟩")
print("Probability of |0⟩:", custom_state[0] ** 2)
print("Probability of |1⟩:", custom_state[1] ** 2)

Answer1:  [1 0]
Answer2:  [0 1]
Answer3:  [1 2 3 4]
Answer4:  <class 'numpy.ndarray'>
Answer5:  [0.5  0.25 0.25]
[[1 0]
 [0 1]] : Answer6
Answer7:  [1 0]
Answer8:  [0 1]
Answer9:  [0.5 0.5]
Answer10:  [45 55]
Answer11:  [10 20 30]
Answer12:  [ 1 -1]
Answer13:  [0.707 0.707]
Answer15: [0.6 0.8]
0.6 is amplitude of |0⟩
0.8 is amplitude of |1⟩
Probability of |0⟩: 0.36
Probability of |1⟩: 0.6400000000000001


## 2. 1D Arrays


A 1D NumPy array behaves like a vector.

In quantum computing, a single-qubit state is commonly represented as a 1D array with 2 values.

### Example

In [5]:
import numpy as np

zero_state = np.array([1, 0])
one_state = np.array([0, 1])

print("Zero state:", zero_state)
print("One state:", one_state)

Zero state: [1 0]
One state: [0 1]


### Practice Questions

1. Create a 1D array `[1, 0]`.
2. Create a 1D array `[0, 1]`.
3. Create a 1D array `[1, 2, 3]`.
4. Create a 1D array of four values `[1, 0, 0, 0]`.
5. Print the first value of a 1D array.
6. Print the second value of a 1D array.
7. Create a 1D array representing `|0⟩`.
8. Create a 1D array representing `|1⟩`.
9. Create a 1D array representing `|00⟩` as `[1, 0, 0, 0]`.
10. Create a 1D array representing `|01⟩` as `[0, 1, 0, 0]`.
11. Create a 1D array representing equal probabilities `[0.25, 0.25, 0.25, 0.25]`.
12. Add two 1D NumPy arrays.
13. Multiply a 1D NumPy array by 2.
14. Subtract one 1D NumPy array from another.
15. Explain why a state vector is usually a 1D array.

In [6]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Create a 1D array `[1, 0]`.
zero_state = np.array([1,0])
# 2. Create a 1D array `[0, 1]`.
one_state = np.array([0,1])
# 3. Create a 1D array `[1, 2, 3]`.
arr3 = np.array([1,2,3])
# 4. Create a 1D array of four values `[1, 0, 0, 0]`.
arr4 = np.array([1,0,0,0])
# 5. Print the first value of a 1D array.
print(arr4[0])
# 6. Print the second value of a 1D array.
print(arr4[1])
# 7. Create a 1D array representing `|0⟩`.
vect_zero = np.array([1,0])
# 8. Create a 1D array representing `|1⟩`.
vect_one = np.array([0,1])
# 9. Create a 1D array representing `|00⟩` as `[1, 0, 0, 0]`.
zero_zero_state = np.array([1,0,0,0])
# 10. Create a 1D array representing `|01⟩` as `[0, 1, 0, 0]`.
zero_one_state = np.array([0,1,0,0])
# 11. Create a 1D array representing equal probabilities `[0.25, 0.25, 0.25, 0.25]`.
equal_probabilities = np.array([0.25, 0.25, 0.25, 0.25])
# 12. Add two 1D NumPy arrays.
sum_arr = zero_state+one_state
print(sum_arr)
# 13. Multiply a 1D NumPy array by 2.
mul_by_2 = 2*arr3
print(mul_by_2)
# 14. Subtract one 1D NumPy array from another.
sub_arr =zero_one_state-zero_zero_state
print(sub_arr)
# 15. Explain why a state vector is usually a 1D array.
"""A state vector is usually a 1D array because it represents a single list of amplitudes for all possible quantum basis states. For example, a 1-qubit state has two basis states, `|0⟩` and `|1⟩`, so we can store their amplitudes as `[1, 0]` or `[0, 1]`. For 2 qubits, there are four basis states: `|00⟩`, `|01⟩`, `|10⟩`, and `|11⟩`, so the state vector has four values like `[1, 0, 0, 0]`. Each position in the array tells how much amplitude that basis state has. Since we only need one ordered list of values, a 1D array is enough to represent the quantum state."""

1
0
[1 1]
[2 4 6]
[-1  1  0  0]


'A state vector is usually a 1D array because it represents a single list of amplitudes for all possible quantum basis states. For example, a 1-qubit state has two basis states, `|0⟩` and `|1⟩`, so we can store their amplitudes as `[1, 0]` or `[0, 1]`. For 2 qubits, there are four basis states: `|00⟩`, `|01⟩`, `|10⟩`, and `|11⟩`, so the state vector has four values like `[1, 0, 0, 0]`. Each position in the array tells how much amplitude that basis state has. Since we only need one ordered list of values, a 1D array is enough to represent the quantum state.'

## 3. 2D Arrays


A 2D NumPy array behaves like a matrix.

In quantum computing, quantum gates are represented as matrices.

### Example

In [7]:
import numpy as np

identity_gate = np.array([
    [1, 0],
    [0, 1]
])

print(identity_gate)

[[1 0]
 [0 1]]


### Practice Questions

1. Create a 2D array `[[1, 0], [0, 1]]`.
2. Create a 2D array `[[0, 1], [1, 0]]`.
3. Create a 2D array `[[1, 0], [0, -1]]`.
4. Create a 3x3 matrix using nested lists.
5. Print the first row of a 2D array.
6. Print the second row of a 2D array.
7. Print the value at row 0, column 0.
8. Print the value at row 0, column 1.
9. Print the value at row 1, column 0.
10. Print the value at row 1, column 1.
11. Create the identity gate manually using `np.array()`.
12. Create the Pauli-X gate manually using `np.array()`.
13. Create the Pauli-Z gate manually using `np.array()`.
14. Create a 2D array with decimal values.
15. Explain why gates are represented as 2D arrays.

In [8]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Create a 2D array `[[1, 0], [0, 1]]`.
I = np.array([
    [1,0],
    [0,1]
])
print(I)
# 2. Create a 2D array `[[0, 1], [1, 0]]`.
X = np.array([
    [0,1],
    [1,0]
])
print(X)
# 3. Create a 2D array `[[1, 0], [0, -1]]`.
arr3 = np.array([
    [1,0],
    [0,-1]
])
print(arr3)
# 4. Create a 3x3 matrix using nested lists.
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)
# 5. Print the first row of a 2D array.
print(I[0])
# 6. Print the second row of a 2D array.
print(I[1])
# 7. Print the value at row 0, column 0.
print(I[0,0])
# 8. Print the value at row 0, column 1.
print(I[0,1])
# 9. Print the value at row 1, column 0.
print(I[1,0])
# 10. Print the value at row 1, column 1.
print(I[1,1])
# 11. Create the identity gate manually using `np.array()`.
I = np.array([
    [1,0],
    [0,1]
])
# 12. Create the Pauli-X gate manually using `np.array()`.
X = np.array([
    [0,1],
    [1,0]
])
# 13. Create the Pauli-Z gate manually using `np.array()`.
Z = np.array([
    [1,0],
    [0,-1]
])
# 14. Create a 2D array with decimal values.
print(np.eye(2))
# 15. Explain why gates are represented as 2D arrays.
"""Gates are represented as 2D arrays because quantum gates act like **matrices** that transform a quantum state vector. A state vector is usually a 1D array, such as `[1, 0]` for `|0⟩`, and a gate needs rows and columns to describe how each input state changes into an output state. For example, the Pauli-Z gate is `[[1, 0], [0, -1]]`, where the first row/column affects `|0⟩` and the second affects `|1⟩`. When we apply a gate, we multiply the 2D gate matrix with the 1D state vector to get a new state vector. So, gates are 2D arrays because they represent transformations, not just a list of amplitudes.
"""

[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 1  0]
 [ 0 -1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 0]
[0 1]
1
0
0
1
[[1. 0.]
 [0. 1.]]


'Gates are represented as 2D arrays because quantum gates act like **matrices** that transform a quantum state vector. A state vector is usually a 1D array, such as `[1, 0]` for `|0⟩`, and a gate needs rows and columns to describe how each input state changes into an output state. For example, the Pauli-Z gate is `[[1, 0], [0, -1]]`, where the first row/column affects `|0⟩` and the second affects `|1⟩`. When we apply a gate, we multiply the 2D gate matrix with the 1D state vector to get a new state vector. So, gates are 2D arrays because they represent transformations, not just a list of amplitudes.\n'

## 4. Array Shape


`.shape` tells you the dimensions of an array.

For quantum computing:

- 1-qubit state: shape `(2,)`
- 1-qubit gate: shape `(2, 2)`
- 2-qubit state: shape `(4,)`
- 2-qubit gate: shape `(4, 4)`

### Example

In [9]:
import numpy as np

state = np.array([1, 0])
gate = np.array([
    [0, 1],
    [1, 0]
])

print(state.shape)
print(gate.shape)

(2,)
(2, 2)


### Practice Questions

1. Print the shape of `[1, 0]`.
2. Print the shape of `[0, 1]`.
3. Print the shape of `[[1, 0], [0, 1]]`.
4. Print the shape of a 3-value 1D array.
5. Print the shape of a 3x3 matrix.
6. Create a 2-qubit state vector and print its shape.
7. Create a 4x4 matrix and print its shape.
8. Check whether a single-qubit state has shape `(2,)`.
9. Check whether a single-qubit gate has shape `(2, 2)`.
10. Write a function that prints the shape of any array.
11. Create a zero state of size 4 and print its shape.
12. Create an identity matrix of size 4 and print its shape.
13. Explain the difference between shape `(2,)` and `(2, 1)`.
14. Create an array with shape `(2, 1)`.
15. Create an array with shape `(1, 2)`.

In [10]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Print the shape of `[1, 0]`.
print(zero_state.shape)
# 2. Print the shape of `[0, 1]`.
print(one_state.shape)
# 3. Print the shape of `[[1, 0], [0, 1]]`.
print(I.shape)
# 4. Print the shape of a 3-value 1D array.
arr4 = np.array([1,2,3])
print(arr4.shape)
# 5. Print the shape of a 3x3 matrix.
print(matrix.shape)
# 6. Create a 2-qubit state vector and print its shape.
two_quibit_state_vector = np.array([1,0,0,0])
print(two_quibit_state_vector.shape)
# 7. Create a 4x4 matrix and print its shape.
matrix_four_four = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])
print(matrix_four_four.shape)
# 8. Check whether a single-qubit state has shape `(2,)`.
print(zero_state.shape==(2,))
# 9. Check whether a single-qubit gate has shape `(2, 2)`.
print(I.shape==(2,2))
# 10. Write a function that prints the shape of any array.
def getShape(arr):
    return arr.shape
print("Shape of zero_one_state through func",getShape(zero_one_state))

# 11. Create a zero state of size 4 and print its shape.
zero_zero_state = np.array([1,0,0,0])
print(zero_zero_state.shape)
# 12. Create an identity matrix of size 4 and print its shape.
I4 = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])
print(I4.shape)
# 13. Explain the difference between shape `(2,)` and `(2, 1)`.
"""Shape (2,) means a 1D array with 2 elements. In quantum computing, it can represent a 1-qubit state vector, such as |0⟩ = [1, 0]. Shape (2, 2) means a 2D array with 2 rows and 2 columns. It is commonly used to represent a single-qubit gate, such as the Identity gate or Pauli-X gate."""
# 14. Create an array with shape `(2, 1)`.
r2_c1 = np.array([
    [1],
    [2]
])
# 15. Create an array with shape `(1, 2)`.
r1_c2 = np.array([[1,2]])

(2,)
(2,)
(2, 2)
(3,)
(3, 3)
(4,)
(4, 4)
True
True
Shape of zero_one_state through func (4,)
(4,)
(4, 4)


## 5. Array Indexing


Indexing is used to access specific values.

For a quantum state vector:

- index `0` usually corresponds to amplitude of `|0⟩`
- index `1` usually corresponds to amplitude of `|1⟩`

### Example

In [11]:
import numpy as np
state = np.array([1, 0])

print(state[0])
print(state[1])

1
0


### Practice Questions

1. Access the first element of `[1, 0]`.
2. Access the second element of `[1, 0]`.
3. Access the first element of `[0, 1]`.
4. Access the second element of `[0, 1]`.
5. Access the value at row 0, column 0 in `[[1, 0], [0, 1]]`.
6. Access the value at row 0, column 1 in `[[1, 0], [0, 1]]`.
7. Access the value at row 1, column 0 in `[[1, 0], [0, 1]]`.
8. Access the value at row 1, column 1 in `[[1, 0], [0, 1]]`.
9. Create an array `[10, 20, 30, 40]` and access the last element.
10. Use negative indexing to access the last value.
11. Use negative indexing to access the second-last value.
12. Create a quantum state and print its `|0⟩` amplitude.
13. Create a quantum state and print its `|1⟩` amplitude.
14. Create an X gate and access all four values one by one.
15. Explain why indexing is useful for reading amplitudes.

In [12]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Access the first element of `[1, 0]`.
print(zero_state[0])
# 2. Access the second element of `[1, 0]`.
print(zero_state[1])
# 3. Access the first element of `[0, 1]`.
print(one_state[0])
# 4. Access the second element of `[0, 1]`.
print(one_state[1])
# 5. Access the value at row 0, column 0 in `[[1, 0], [0, 1]]`.
print(I[0][0])
# 6. Access the value at row 0, column 1 in `[[1, 0], [0, 1]]`.
print(I[0][1])
# 7. Access the value at row 1, column 0 in `[[1, 0], [0, 1]]`.
print(I[1][0])
# 8. Access the value at row 1, column 1 in `[[1, 0], [0, 1]]`.
print(I[1][1])
# 9. Create an array `[10, 20, 30, 40]` and access the last element.
arr9 = np.array([10, 20, 30, 40])
print(arr9[-1])
# 10. Use negative indexing to access the last value.
print(arr9[-1])
# 11. Use negative indexing to access the second-last value.
print(arr9[-2])
# 12. Create a quantum state and print its `|0⟩` amplitude.
print(zero_state[0])
# 13. Create a quantum state and print its `|1⟩` amplitude.
print(zero_state[1])
# 14. Create an X gate and access all four values one by one.
print(X[0][0])
print(X[0][1])
print(X[1][0])
print(X[1][1])
# 15. Explain why indexing is useful for reading amplitudes.
"""
Indexing is useful for reading amplitudes because each position in a quantum state vector represents one basis state. For example, in a 1-qubit state [1, 0], index 0 represents the amplitude of |0⟩, and index 1 represents the amplitude of |1⟩. So, using state[0] tells us how much amplitude the state has for |0⟩, and state[1] tells us how much amplitude it has for |1⟩. For a 2-qubit state like [1, 0, 0, 0], the indexes represent |00⟩, |01⟩, |10⟩, and |11⟩. This makes indexing important because it lets us directly check the amplitude of any specific quantum basis state. 
"""

1
0
0
1
1
0
0
1
40
40
30
1
0
0
1
1
0


'\nIndexing is useful for reading amplitudes because each position in a quantum state vector represents one basis state. For example, in a 1-qubit state [1, 0], index 0 represents the amplitude of |0⟩, and index 1 represents the amplitude of |1⟩. So, using state[0] tells us how much amplitude the state has for |0⟩, and state[1] tells us how much amplitude it has for |1⟩. For a 2-qubit state like [1, 0, 0, 0], the indexes represent |00⟩, |01⟩, |10⟩, and |11⟩. This makes indexing important because it lets us directly check the amplitude of any specific quantum basis state. \n'

## 6. Array Slicing


Slicing is used to access a part of an array.

For matrices, slicing helps you access rows, columns, or sub-matrices.

### Example

In [13]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0:3])
print(arr[2:])

[10 20 30]
[30 40 50]


### Practice Questions

1. Slice the first two values from `[10, 20, 30, 40]`.
2. Slice the last two values from `[10, 20, 30, 40]`.
3. Slice values from index 1 to index 3.
4. Create a 2D matrix and get the first row.
5. Create a 2D matrix and get the second row.
6. Create a 2D matrix and get the first column.
7. Create a 2D matrix and get the second column.
8. Slice a 3x3 matrix to get the first two rows.
9. Slice a 3x3 matrix to get the first two columns.
10. Slice a 3x3 matrix to get the center value.
11. Create a 4-value quantum state and slice the first two amplitudes.
12. Create a 4-value quantum state and slice the last two amplitudes.
13. Use `:` to print all rows of one column.
14. Use `:` to print one full row.
15. Explain how slicing helps inspect matrices.

In [14]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Slice the first two values from `[10, 20, 30, 40]`.
arr1 =np.array([10, 20, 30, 40])
print(arr1[:2])
# 2. Slice the last two values from `[10, 20, 30, 40]`.
print(arr1[2:])
# 3. Slice values from index 1 to index 3.
print(arr1[1:3])
# 4. Create a 2D matrix and get the first row.
print(I[0,:])
# 5. Create a 2D matrix and get the second row.
print(I[1,:])
# 6. Create a 2D matrix and get the first column.
print(I[:,0])
# 7. Create a 2D matrix and get the second column.
print(I[:,1])
# 8. Slice a 3x3 matrix to get the first two rows.
I3 = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print(I3[:2,:])
# 9. Slice a 3x3 matrix to get the first two columns.
print(I3[:,:2])
# 10. Slice a 3x3 matrix to get the center value.
print(I3[1,1])
# 11. Create a 4-value quantum state and slice the first two amplitudes.
print(zero_zero_state[:2])
# 12. Create a 4-value quantum state and slice the last two amplitudes.
print(zero_zero_state[2:])
# 13. Use `:` to print all rows of one column.
print(I3[:,0])
# 14. Use `:` to print one full row.
print("row",I3[1,:])
# 15. Explain how slicing helps inspect matrices.
""" 
Slicing helps inspect matrices because it allows us to look at a specific part of a matrix without printing or checking the whole matrix manually. For example, if a matrix has many rows and columns, we can use slicing to view only the first row, first column, first two rows, or any smaller section. This makes it easier to understand the structure of the matrix and debug mistakes.
"""

[10 20]
[30 40]
[20 30]
[1 0]
[0 1]
[1 0]
[0 1]
[[1 0 0]
 [0 1 0]]
[[1 0]
 [0 1]
 [0 0]]
1
[1 0]
[0 0]
[1 0 0]
row [0 1 0]


' \nSlicing helps inspect matrices because it allows us to look at a specific part of a matrix without printing or checking the whole matrix manually. For example, if a matrix has many rows and columns, we can use slicing to view only the first row, first column, first two rows, or any smaller section. This makes it easier to understand the structure of the matrix and debug mistakes.\n'

## 7. `np.zeros()`


`np.zeros()` creates an array filled with zeros.

This is useful when creating empty state vectors and then setting one amplitude manually.

### Example

In [15]:
state = np.zeros(2)
state[0] = 1

print(state)

[1. 0.]


### Practice Questions

1. Create a 1D zero array of size 2.
2. Create a 1D zero array of size 4.
3. Create a 2x2 zero matrix.
4. Create a 3x3 zero matrix.
5. Create a zero array and set the first value to 1.
6. Create a zero array and set the second value to 1.
7. Create `[1, 0]` using `np.zeros()`.
8. Create `[0, 1]` using `np.zeros()`.
9. Create `[1, 0, 0, 0]` using `np.zeros()`.
10. Create `[0, 1, 0, 0]` using `np.zeros()`.
11. Create a zero matrix and update one value.
12. Create a 4x4 zero matrix.
13. Print the shape of a zero vector.
14. Print the shape of a zero matrix.
15. Explain why `np.zeros()` is useful for initializing quantum states.

In [18]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Create a 1D zero array of size 2.
zero_size_2 = np.zeros(2)
print("Answer1:", zero_size_2)

# 2. Create a 1D zero array of size 4.
zero_size_4 = np.zeros(4)
print("Answer2:", zero_size_4)

# 3. Create a 2x2 zero matrix.
zero_matrix_2x2 = np.zeros((2, 2))
print("Answer3:", zero_matrix_2x2)

# 4. Create a 3x3 zero matrix.
zero_matrix_3x3 = np.zeros((3, 3))
print("Answer4:", zero_matrix_3x3)

# 5. Create a zero array and set the first value to 1.
arr5 = np.zeros(2)
arr5[0] = 1
print("Answer5:", arr5)

# 6. Create a zero array and set the second value to 1.
arr6 = np.zeros(2)
arr6[1] = 1
print("Answer6:", arr6)

# 7. Create `[1, 0]` using `np.zeros()`.
zero_state_from_zeros = np.zeros(2)
zero_state_from_zeros[0] = 1
print("Answer7:", zero_state_from_zeros)

# 8. Create `[0, 1]` using `np.zeros()`.
one_state_from_zeros = np.zeros(2)
one_state_from_zeros[1] = 1
print("Answer8:", one_state_from_zeros)

# 9. Create `[1, 0, 0, 0]` using `np.zeros()`.
zero_zero_state_from_zeros = np.zeros(4)
zero_zero_state_from_zeros[0] = 1
print("Answer9:", zero_zero_state_from_zeros)

# 10. Create `[0, 1, 0, 0]` using `np.zeros()`.
zero_one_state_from_zeros = np.zeros(4)
zero_one_state_from_zeros[1] = 1
print("Answer10:", zero_one_state_from_zeros)

# 11. Create a zero matrix and update one value.
zero_matrix = np.zeros((2, 2))
zero_matrix[0, 1] = 1
print("Answer11:", zero_matrix)

# 12. Create a 4x4 zero matrix.
zero_matrix_4x4 = np.zeros((4, 4))
print("Answer12:", zero_matrix_4x4)

# 13. Print the shape of a zero vector.
print("Answer13:", zero_size_4.shape)

# 14. Print the shape of a zero matrix.
print("Answer14:", zero_matrix_4x4.shape)

# 15. Explain why `np.zeros()` is useful for initializing quantum states.
"""
np.zeros() is useful for initializing quantum states because it creates an empty state vector with all amplitudes set to 0. After that, we can manually set the amplitude of one basis state to 1. For example, a 2-qubit |00⟩ state can be created by starting with np.zeros(4) and setting index 0 to 1. This is helpful when we want to create a specific basis state cleanly.
"""

Answer1: [0. 0.]
Answer2: [0. 0. 0. 0.]
Answer3: [[0. 0.]
 [0. 0.]]
Answer4: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Answer5: [1. 0.]
Answer6: [0. 1.]
Answer7: [1. 0.]
Answer8: [0. 1.]
Answer9: [1. 0. 0. 0.]
Answer10: [0. 1. 0. 0.]
Answer11: [[0. 1.]
 [0. 0.]]
Answer12: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Answer13: (4,)
Answer14: (4, 4)


'\nnp.zeros() is useful for initializing quantum states because it creates an empty state vector with all amplitudes set to 0. After that, we can manually set the amplitude of one basis state to 1. For example, a 2-qubit |00⟩ state can be created by starting with np.zeros(4) and setting index 0 to 1. This is helpful when we want to create a specific basis state cleanly.\n'

## 8. `np.ones()`


`np.ones()` creates an array filled with ones.

Important: an array of ones is usually not automatically a valid quantum state until normalized.

### Example

In [ ]:
arr = np.ones(4)
print(arr)

[1. 1. 1. 1.]


### Practice Questions

1. Create a 1D ones array of size 2.
2. Create a 1D ones array of size 4.
3. Create a 2x2 ones matrix.
4. Create a 3x3 ones matrix.
5. Multiply a ones array by 2.
6. Divide a ones array by 2.
7. Create `[0.5, 0.5]` using `np.ones()`.
8. Create `[0.25, 0.25, 0.25, 0.25]` using `np.ones()`.
9. Create a 2x2 matrix where all values are `0.5`.
10. Print the shape of a ones vector.
11. Print the shape of a ones matrix.
12. Create an array of ones and normalize it manually for size 2.
13. Create an array of ones and normalize it manually for size 4.
14. Check the sum of probabilities after normalization.
15. Explain why `[1, 1]` is not a normalized quantum state.

In [19]:
# Practice workspace
import numpy as np
# Write your answers here
# 1. Create a 1D ones array of size 2.
ones_size_2 = np.ones(2)
print("Answer1:", ones_size_2)

# 2. Create a 1D ones array of size 4.
ones_size_4 = np.ones(4)
print("Answer2:", ones_size_4)

# 3. Create a 2x2 ones matrix.
ones_matrix_2x2 = np.ones((2, 2))
print("Answer3:", ones_matrix_2x2)

# 4. Create a 3x3 ones matrix.
ones_matrix_3x3 = np.ones((3, 3))
print("Answer4:", ones_matrix_3x3)

# 5. Multiply a ones array by 2.
arr5 = np.ones(4) * 2
print("Answer5:", arr5)

# 6. Divide a ones array by 2.
arr6 = np.ones(4) / 2
print("Answer6:", arr6)

# 7. Create `[0.5, 0.5]` using `np.ones()`.
arr7 = np.ones(2) * 0.5
print("Answer7:", arr7)

# 8. Create `[0.25, 0.25, 0.25, 0.25]` using `np.ones()`.
arr8 = np.ones(4) * 0.25
print("Answer8:", arr8)

# 9. Create a 2x2 matrix where all values are `0.5`.
arr9 = np.ones((2, 2)) * 0.5
print("Answer9:", arr9)

# 10. Print the shape of a ones vector.
print("Answer10:", ones_size_4.shape)

# 11. Print the shape of a ones matrix.
print("Answer11:", ones_matrix_2x2.shape)

# 12. Create an array of ones and normalize it manually for size 2.
state_size_2 = np.ones(2)
normalized_state_2 = state_size_2 / np.sqrt(2)
print("Answer12:", normalized_state_2)

# 13. Create an array of ones and normalize it manually for size 4.
state_size_4 = np.ones(4)
normalized_state_4 = state_size_4 / np.sqrt(4)
print("Answer13:", normalized_state_4)

# 14. Check the sum of probabilities after normalization.
probabilities_2 = np.abs(normalized_state_2) ** 2
probabilities_4 = np.abs(normalized_state_4) ** 2
print("Answer14 size 2 probability sum:", np.sum(probabilities_2))
print("Answer14 size 4 probability sum:", np.sum(probabilities_4))

# 15. Explain why `[1, 1]` is not a normalized quantum state.
"""
[1, 1] is not a normalized quantum state because the total probability becomes 1² + 1² = 2, but a valid quantum state must have total probability equal to 1. To normalize it, we divide by sqrt(2), which gives [1/sqrt(2), 1/sqrt(2)]. Then each probability is 0.5 and the total probability becomes 1.
"""

Answer1: [1. 1.]
Answer2: [1. 1. 1. 1.]
Answer3: [[1. 1.]
 [1. 1.]]
Answer4: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Answer5: [2. 2. 2. 2.]
Answer6: [0.5 0.5 0.5 0.5]
Answer7: [0.5 0.5]
Answer8: [0.25 0.25 0.25 0.25]
Answer9: [[0.5 0.5]
 [0.5 0.5]]
Answer10: (4,)
Answer11: (2, 2)
Answer12: [0.70710678 0.70710678]
Answer13: [0.5 0.5 0.5 0.5]
Answer14 size 2 probability sum: 0.9999999999999998
Answer14 size 4 probability sum: 1.0


'\n[1, 1] is not a normalized quantum state because the total probability becomes 1² + 1² = 2, but a valid quantum state must have total probability equal to 1. To normalize it, we divide by sqrt(2), which gives [1/sqrt(2), 1/sqrt(2)]. Then each probability is 0.5 and the total probability becomes 1.\n'

## 9. `np.eye()`


`np.eye()` creates an identity matrix.

In quantum computing, the identity gate keeps the state unchanged.

### Example

In [ ]:
I = np.eye(2)

state = np.array([1, 0])
new_state = I @ state

print(I)
print(new_state)

[[1. 0.]
 [0. 1.]]
[1. 0.]


### Practice Questions

1. Create a 2x2 identity matrix using `np.eye()`.
2. Create a 3x3 identity matrix using `np.eye()`.
3. Create a 4x4 identity matrix using `np.eye()`.
4. Apply a 2x2 identity matrix to `[1, 0]`.
5. Apply a 2x2 identity matrix to `[0, 1]`.
6. Verify that identity does not change `|0⟩`.
7. Verify that identity does not change `|1⟩`.
8. Print the shape of `np.eye(2)`.
9. Print the shape of `np.eye(4)`.
10. Create identity manually using `np.array()` and compare with `np.eye(2)`.
11. Create a 2-qubit identity gate using `np.eye(4)`.
12. Apply a 4x4 identity gate to `[1, 0, 0, 0]`.
13. Access the diagonal values of an identity matrix.
14. Access non-diagonal values of an identity matrix.
15. Explain why identity is useful in quantum circuits.

In [ ]:
# Practice workspace
# Write your answers here

## 10. `np.sqrt()`


`np.sqrt()` calculates square roots.

Quantum states often use `1 / sqrt(2)` for equal superposition.

### Example

In [ ]:
value = 1 / np.sqrt(2)
print(value)

plus_state = np.array([value, value])
print(plus_state)

0.7071067811865475
[0.70710678 0.70710678]


### Practice Questions

1. Calculate `np.sqrt(2)`.
2. Calculate `np.sqrt(4)`.
3. Calculate `1 / np.sqrt(2)`.
4. Create the plus state `[1/sqrt(2), 1/sqrt(2)]`.
5. Create the minus state `[1/sqrt(2), -1/sqrt(2)]`.
6. Square `1 / np.sqrt(2)` and check the result.
7. Calculate probabilities for the plus state.
8. Calculate probabilities for the minus state.
9. Create the Hadamard matrix using `np.sqrt()`.
10. Apply Hadamard to `|0⟩`.
11. Apply Hadamard to `|1⟩`.
12. Check if probabilities sum to 1.
13. Use `np.sqrt()` to normalize `[1, 1]`.
14. Use `np.sqrt()` to normalize `[1, 1, 1, 1]`.
15. Explain why `sqrt` appears often in quantum computing.

In [ ]:
# Practice workspace
# Write your answers here

## 11. Python Lists vs NumPy Arrays


Python lists are general-purpose containers.

NumPy arrays are designed for numerical computing.

This difference is critical for quantum software because states and gates require mathematical operations.

### Example

In [ ]:
list_a = [1, 2]
list_b = [3, 4]

array_a = np.array([1, 2])
array_b = np.array([3, 4])

print("List addition:", list_a + list_b)
print("Array addition:", array_a + array_b)

List addition: [1, 2, 3, 4]
Array addition: [4 6]


### Practice Questions

1. Add two Python lists and observe the result.
2. Add two NumPy arrays and observe the result.
3. Multiply a Python list by 2 and observe the result.
4. Multiply a NumPy array by 2 and observe the result.
5. Subtract two NumPy arrays.
6. Try subtracting two Python lists and observe the error.
7. Create a Python list `[1, 0]`.
8. Create a NumPy array `[1, 0]`.
9. Print the type of both.
10. Convert a Python list into a NumPy array.
11. Add `[1, 0]` and `[0, 1]` as lists.
12. Add `[1, 0]` and `[0, 1]` as arrays.
13. Explain why list addition is not useful for quantum states.
14. Explain why NumPy array addition is useful for numerical work.
15. Write one example where NumPy behavior is better than list behavior.

In [ ]:
# Practice workspace
# Write your answers here

## 12. Quantum States as Vectors


A quantum state vector stores amplitudes.

For a single qubit:

- `|0⟩ = [1, 0]`
- `|1⟩ = [0, 1]`
- `|+⟩ = [1/sqrt(2), 1/sqrt(2)]`
- `|-⟩ = [1/sqrt(2), -1/sqrt(2)]`

### Example

In [ ]:
zero = np.array([1, 0])
one = np.array([0, 1])
plus = np.array([1 / np.sqrt(2), 1 / np.sqrt(2)])
minus = np.array([1 / np.sqrt(2), -1 / np.sqrt(2)])

print("zero:", zero)
print("one:", one)
print("plus:", plus)
print("minus:", minus)

zero: [1 0]
one: [0 1]
plus: [0.70710678 0.70710678]
minus: [ 0.70710678 -0.70710678]


### Practice Questions

1. Create the `|0⟩` state.
2. Create the `|1⟩` state.
3. Create the `|+⟩` state.
4. Create the `|-⟩` state.
5. Print the shape of each state.
6. Print the first amplitude of `|0⟩`.
7. Print the second amplitude of `|1⟩`.
8. Calculate probabilities of `|0⟩`.
9. Calculate probabilities of `|1⟩`.
10. Calculate probabilities of `|+⟩`.
11. Calculate probabilities of `|-⟩`.
12. Check whether probabilities sum to 1 for each state.
13. Create a custom state `[0.6, 0.8]` and check probabilities.
14. Normalize a custom state `[1, 1]`.
15. Explain the difference between amplitude and probability.

In [ ]:
# Practice workspace
# Write your answers here

## 13. Quantum Gates as Matrices


Quantum gates are matrices that transform quantum state vectors.

Common single-qubit gates:

- I: identity
- X: bit flip
- Z: phase flip
- H: creates superposition

### Example

In [ ]:
I = np.eye(2)

X = np.array([
    [0, 1],
    [1, 0]
])

Z = np.array([
    [1, 0],
    [0, -1]
])

H = (1 / np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

print("I:\n", I)
print("X:\n", X)
print("Z:\n", Z)
print("H:\n", H)

I:
 [[1. 0.]
 [0. 1.]]
X:
 [[0 1]
 [1 0]]
Z:
 [[ 1  0]
 [ 0 -1]]
H:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


### Practice Questions

1. Create the identity gate.
2. Create the Pauli-X gate.
3. Create the Pauli-Z gate.
4. Create the Hadamard gate.
5. Print the shape of each gate.
6. Access the first row of X.
7. Access the second row of X.
8. Access the diagonal of Z manually.
9. Apply I to `|0⟩`.
10. Apply I to `|1⟩`.
11. Apply X to `|0⟩`.
12. Apply X to `|1⟩`.
13. Apply Z to `|0⟩`.
14. Apply Z to `|1⟩`.
15. Apply H to `|0⟩` and explain the result.

In [ ]:
# Practice workspace
# Write your answers here

## 14. Probabilities from Amplitudes


Quantum states contain amplitudes.

Measurement probabilities are calculated as:

`np.abs(state) ** 2`

This works for both real and complex amplitudes.

### Example

In [ ]:
state = np.array([1 / np.sqrt(2), 1 / np.sqrt(2)])

probabilities = np.abs(state) ** 2

print(probabilities)
print("Total probability:", np.sum(probabilities))

[0.5 0.5]
Total probability: 0.9999999999999998


### Practice Questions

1. Calculate probabilities for `|0⟩`.
2. Calculate probabilities for `|1⟩`.
3. Calculate probabilities for `|+⟩`.
4. Calculate probabilities for `|-⟩`.
5. Check total probability for `|0⟩`.
6. Check total probability for `|+⟩`.
7. Create state `[0.6, 0.8]` and calculate probabilities.
8. Check if `[0.6, 0.8]` is normalized.
9. Create state `[1, 1]` and calculate probabilities.
10. Normalize `[1, 1]` and calculate probabilities again.
11. Use `np.abs()` on a negative amplitude.
12. Use `np.abs()` on a complex amplitude.
13. Create a state with complex amplitude `[1/sqrt(2), 1j/sqrt(2)]`.
14. Calculate probabilities for the complex state.
15. Explain why probabilities must sum to 1.

In [ ]:
# Practice workspace
# Write your answers here

## 15. Basic Gate Application


The most important quantum simulation operation is:

`new_state = gate @ state`

The `@` operator performs matrix multiplication.

### Example

In [ ]:
zero = np.array([1, 0])

X = np.array([
    [0, 1],
    [1, 0]
])

new_state = X @ zero
print(new_state)

[0 1]


### Practice Questions

1. Apply X to `|0⟩`.
2. Apply X to `|1⟩`.
3. Apply I to `|0⟩`.
4. Apply I to `|1⟩`.
5. Apply Z to `|0⟩`.
6. Apply Z to `|1⟩`.
7. Apply H to `|0⟩`.
8. Apply H to `|1⟩`.
9. Apply H twice to `|0⟩`.
10. Apply X twice to `|0⟩`.
11. Apply Z twice to `|1⟩`.
12. Apply X after H to `|0⟩`.
13. Apply H after X to `|0⟩`.
14. Create a function `apply_gate(gate, state)`.
15. Use your function with X, H, and Z gates.

In [ ]:
# Practice workspace
# Write your answers here

## 16. Tensor Product using `np.kron()`


`np.kron()` is used to combine quantum states and gates.

This is essential for multi-qubit quantum computing.

Examples:

- `|00⟩ = np.kron(|0⟩, |0⟩)`
- `|01⟩ = np.kron(|0⟩, |1⟩)`

### Example

In [ ]:
zero = np.array([1, 0])
one = np.array([0, 1])

zero_zero = np.kron(zero, zero)
zero_one = np.kron(zero, one)

print("|00>:", zero_zero)
print("|01>:", zero_one)

|00>: [1 0 0 0]
|01>: [0 1 0 0]


### Practice Questions

1. Create `|00⟩` using `np.kron()`.
2. Create `|01⟩` using `np.kron()`.
3. Create `|10⟩` using `np.kron()`.
4. Create `|11⟩` using `np.kron()`.
5. Print the shape of each 2-qubit state.
6. Create a 2-qubit identity gate using `np.kron(I, I)`.
7. Print the shape of the 2-qubit identity gate.
8. Create `X ⊗ I` using `np.kron(X, I)`.
9. Create `I ⊗ X` using `np.kron(I, X)`.
10. Apply `X ⊗ I` to `|00⟩`.
11. Apply `I ⊗ X` to `|00⟩`.
12. Apply `X ⊗ I` to `|01⟩`.
13. Apply `I ⊗ X` to `|10⟩`.
14. Create `H ⊗ I`.
15. Apply `H ⊗ I` to `|00⟩` and calculate probabilities.

In [ ]:
# Practice workspace
# Write your answers here

# Final Mini Project: 1-Qubit Quantum Simulator

Build a small simulator with these features:

1. Create `|0⟩` and `|1⟩`.
2. Create I, X, Z, and H gates.
3. Apply gates using `@`.
4. Print final state.
5. Print measurement probabilities.
6. Add helper functions:
   - `apply_gate(gate, state)`
   - `get_probabilities(state)`
   - `normalize(state)`

In [ ]:
import numpy as np

def apply_gate(gate, state):
    return gate @ state

def get_probabilities(state):
    return np.abs(state) ** 2

def normalize(state):
    return state / np.linalg.norm(state)

zero = np.array([1, 0])
one = np.array([0, 1])

I = np.eye(2)

X = np.array([
    [0, 1],
    [1, 0]
])

Z = np.array([
    [1, 0],
    [0, -1]
])

H = (1 / np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

state = zero

state = apply_gate(H, state)
print("After H:", state)
print("Probabilities:", get_probabilities(state))

state = apply_gate(X, state)
print("After X:", state)
print("Probabilities:", get_probabilities(state))

After H: [0.70710678 0.70710678]
Probabilities: [0.5 0.5]
After X: [0.70710678 0.70710678]
Probabilities: [0.5 0.5]


# Final Challenge Questions

1. What is the shape of a 1-qubit state?
2. What is the shape of a 1-qubit gate?
3. What is the shape of a 2-qubit state?
4. What is the shape of a 2-qubit gate?
5. Why do we use `np.abs(state) ** 2`?
6. Why is `[1, 1]` not a valid normalized quantum state?
7. What does the X gate do?
8. What does the Z gate do?
9. What does the H gate do?
10. Why is `np.kron()` important?
11. What does `gate @ state` mean?
12. How do you create `|00⟩`?
13. How do you create `|11⟩`?
14. How do you calculate measurement probabilities?
15. What should the total probability always equal?